IsTakip.WebUI/Models/ErrorViewModel.cs
namespace IsTakip.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IsTakip.WebUI/Controllers/DepoController.cs
using IsTakip.Core.Entites;
using IsTakip.Data.Context;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace IsTakip.WebUI.Controllers
{
    public class DepoController : Controller
    {
        // GET: DepoController
        private readonly DataContext _context;

        public DepoController(DataContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            var model = _context.Depo.ToList();
            return View(model);
        }

        // GET: DepoController/Details/5
        public ActionResult Details(int id)
        {
            var model = _context.Depo.Find(id);
            return View(model);
        }

        // GET: DepoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DepoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Depo depo)
        {

            if (depo is null)
            {
                return RedirectToAction(nameof(Index));
            }
            if (ModelState.IsValid)
            {
                _context.Depo.Add(depo);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }
            ViewData["Mesaj"] = "Kaydetme İşlemi Başarılı";
            return View(depo);
        }

        // GET: DepoController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _context.Depo.Find(id);
            return View(model);

        }

        // POST: DepoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Depo depo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    depo.Tanim = depo.Tanim.ToUpper();
                    depo.Aciklama = depo.Aciklama.ToUpper();

                    _context.Depo.Update(depo);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    ModelState.AddModelError("", "Hata oluştu");
                }

            }
            return View(depo);
        }

        // GET: DepoController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _context.Depo.Find(id);
            return View(model);
        }
        // POST: DepoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Depo depo)
        {
            try
            {
                _context.Depo.Remove(depo);
                _context.SaveChanges();
                
            }
            catch
            {
                return View();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

IsTakip.WebUI/Controllers/HomeController.cs
using IsTakip.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IsTakip.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IsTakip.WebUI/Controllers/KullaniciController.cs
using IsTakip.Core.Entites;
using IsTakip.Data.Context;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace IsTakip.WebUI.Controllers
{
    public class KullaniciController : Controller
	{
		private readonly DataContext _context;
		private readonly ILogger<KullaniciController> _logger;
		public KullaniciController(DataContext context,ILogger <KullaniciController>logger)
		{
			_context = context;
			_logger = logger;
		}

		// GET: KullaniciController
		public ActionResult Index()
		{
			var model = _context.Kullanici.ToList();
			return View(model);
		}

		// GET: KullaniciController/Details/5
		public ActionResult Details(int id)
		{
			var model = _context.Kullanici.Find(id);
			return View(model);
		}

		// GET: KullaniciController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: KullaniciController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(Kullanici kullanici)
		{

            if (kullanici is null)
            {
                return RedirectToAction(nameof(Index));
            }
            if (ModelState.IsValid)
            {
                _context.Kullanici.Add(kullanici);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }
            ViewData["Mesaj"] = "Kaydetme İşlemi Başarılı";

            var options = new JsonSerializerOptions { WriteIndented = true };
            var serializedData = JsonSerializer.Serialize<Kullanici>(kullanici, options);
            _logger.LogInformation(serializedData);
            var data = _context.GetById(kullanici.Id);

			
            return View(kullanici);

		}

		// GET: KullaniciController/Edit/5
		public ActionResult Edit(int id)
		{
			var model = _context.Kullanici.Find(id);
			return View(model);

		}

		// POST: KullaniciController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]

		public ActionResult Edit(int id, Kullanici kullanici)
		{
			if (kullanici == null)
			{
				return RedirectToAction(nameof(Index));

			}			
		
			if (ModelState.IsValid)
			{
				try
				{
					kullanici.Ad = kullanici.Ad.ToUpper();
					kullanici.Soyad = kullanici.Soyad.ToUpper();
                    kullanici.RoleTanim = kullanici.RoleTanim;


                    _context.Kullanici.Update(kullanici);
					_context.SaveChanges();
					return RedirectToAction(nameof(Index));
				}
				catch
				{
					ModelState.AddModelError("", "Hata oluştu");
				}


			}

			var options = new JsonSerializerOptions { WriteIndented = true };
            var serializedData = JsonSerializer.Serialize<Kullanici>(kullanici, options);
            _logger.LogInformation(serializedData);

            return View(kullanici);
		}

		// GET: KullaniciController/Delete/5
		public ActionResult Delete(int id)
		{
			var model = _context.Kullanici.Find(id);
			return View(model);
		}

		// POST: KullaniciController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, Kullanici kullanici)
		{
            try
            {
                _context.Kullanici.Remove(kullanici);
                _context.SaveChanges();
                
            }
            catch
            {
                return View();
            }

            return RedirectToAction(nameof(Index));

        }
	}
}

IsTakip.WebUI/Controllers/LoginController.cs
using IsTakip.Core.Dtos;
using IsTakip.Data.Context;
using Microsoft.AspNetCore.Mvc;

namespace IsTakip.WebUI.Controllers
{
    public class LoginController : Controller
    {
        private readonly DataContext _context;
        public LoginController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
       public IActionResult Index(LoginDto loginDto)
		{
			if (!ModelState.IsValid)
				return View(loginDto);

			var kullanici = _context.Kullanici.Where(t => t.KullaniciKodu == loginDto.KullaniciKodu && t.KullaniciSifre == loginDto.KullaniciSifre && t.Aktif && !t.Silindi).FirstOrDefault();

			if (kullanici is null)
			{
				ModelState.AddModelError(nameof(loginDto.KullaniciSifre), "Kullanıcı Kodu veya şifre hatalı veya kullanıcı aktif değil.");
				return View(loginDto);
			}

			//TempData["degiskenAdi"] = kullanici.Id;

			//	return RedirectToAction(nameof(Index), "Home", new { Id = kullanici.Id });
			return RedirectToAction("Index",
			new RouteValueDictionary(
				new { controller = "Home", action = "Index", Id = kullanici.Id }
			));
		}
    }
}

IsTakip.WebUI/Views/Depo/Create.cshtml
@model IsTakip.Core.Entites.Depo

@{
    ViewData["Title"] = "Create";
}

<h1>Yeni Oluştur</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Tanim" class="control-label"></label>
                <input asp-for="Tanim" class="form-control" />
                <span asp-validation-for="Tanim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aciklama" class="control-label"></label>
                <input asp-for="Aciklama" class="form-control" />
                <span asp-validation-for="Aciklama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Yetkili" class="control-label"></label>
                <input asp-for="Yetkili" class="form-control" />
                <span asp-validation-for="Yetkili" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YetkiliTelefon" class="control-label"></label>
                <input asp-for="YetkiliTelefon" class="form-control" />
                <span asp-validation-for="YetkiliTelefon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OlusturanKullanici" class="control-label"></label>
                <input asp-for="OlusturanKullanici" class="form-control" />
                <span asp-validation-for="OlusturanKullanici" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OlusturanKullaniciId" class="control-label"></label>
                <input asp-for="OlusturanKullaniciId" class="form-control" />
                <span asp-validation-for="OlusturanKullaniciId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OlusturmaTarihi" class="control-label"></label>
                <input asp-for="OlusturmaTarihi" class="form-control" />
                <span asp-validation-for="OlusturmaTarihi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuncelleyenKullanici" class="control-label"></label>
                <input asp-for="GuncelleyenKullanici" class="form-control" />
                <span asp-validation-for="GuncelleyenKullanici" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuncelleyenKullaniciId" class="control-label"></label>
                <input asp-for="GuncelleyenKullaniciId" class="form-control" />
                <span asp-validation-for="GuncelleyenKullaniciId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GüncellemeTarihi" class="control-label"></label>
                <input asp-for="GüncellemeTarihi" class="form-control" />
                <span asp-validation-for="GüncellemeTarihi" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aktif" /> @Html.DisplayNameFor(model => model.Aktif)
                </label>
            </div>
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Silindi" /> @Html.DisplayNameFor(model => model.Silindi)
                </label>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Oluştur" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-warning" asp-action="Index">Listeye Geri Dön</a>
</div>

IsTakip.WebUI/Views/Depo/Delete.cshtml
@model IsTakip.Core.Entites.Depo

@{
    ViewData["Title"] = "Delete";
}

<h3>Silmek istediğine emin misin?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tanim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tanim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aciklama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Yetkili)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Yetkili)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YetkiliTelefon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YetkiliTelefon)
        </dd>    
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aktif)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aktif)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Silindi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Silindi)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a class="btn btn-warning" asp-action="Index">Listeye Geri Dön</a>
    </form>
</div>

IsTakip.WebUI/Views/Depo/Details.cshtml
@model IsTakip.Core.Entites.Depo

@{
    ViewData["Title"] = "Details";
}

<h1>Düzenle</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tanim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tanim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aciklama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Yetkili)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Yetkili)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YetkiliTelefon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YetkiliTelefon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OlusturanKullanici)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OlusturanKullanici)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OlusturanKullaniciId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OlusturanKullaniciId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OlusturmaTarihi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OlusturmaTarihi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuncelleyenKullanici)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuncelleyenKullanici)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuncelleyenKullaniciId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuncelleyenKullaniciId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GüncellemeTarihi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GüncellemeTarihi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aktif)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aktif)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Silindi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Silindi)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model?.Id">Düzenle</a> |
    <a class="btn btn-warning" asp-action="Index">Listeye Geri Dön</a>
</div>

IsTakip.WebUI/Views/Depo/Edit.cshtml
@model IsTakip.Core.Entites.Depo

@{
    ViewData["Title"] = "Edit";
}

<h1>Düzenle</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Tanim" class="control-label"></label>
                <input asp-for="Tanim" class="form-control" />
                <span asp-validation-for="Tanim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aciklama" class="control-label"></label>
                <input asp-for="Aciklama" class="form-control" />
                <span asp-validation-for="Aciklama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Yetkili" class="control-label"></label>
                <input asp-for="Yetkili" class="form-control" />
                <span asp-validation-for="Yetkili" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YetkiliTelefon" class="control-label"></label>
                <input asp-for="YetkiliTelefon" class="form-control" />
                <span asp-validation-for="YetkiliTelefon" class="text-danger"></span>
            </div>
          
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aktif" /> @Html.DisplayNameFor(model => model.Aktif)
                </label>
            </div>
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Silindi" /> @Html.DisplayNameFor(model => model.Silindi)
                </label>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-warning" asp-action="Index">Listeye Geri Dön</a>
</div>

IsTakip.WebUI/Views/Depo/Index.cshtml
@model IEnumerable<IsTakip.Core.Entites.Depo>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a class="btn btn-outline-warning" asp-action="Create">Yeni Oluştur</a>
</p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tanim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aciklama)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Yetkili)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YetkiliTelefon)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tanim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aciklama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Yetkili)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YetkiliTelefon)
            </td>
           
            <td>
                <a class="btn btn-outline-success" asp-action="Edit" asp-route-id="@item.Id">Düzenle</a> |
                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Detaylar</a> |
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
            </td>
        </tr>
}
    </tbody>
</table>

IsTakip.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IsTakip.WebUI/Views/Kullanici/Create.cshtml
@using IsTakip.Core.Entites;
@using IsTakip.Core.Enums;
@model IsTakip.Core.Entites.Kullanici

@{
    ViewData["Title"] = "Create";
}

<h1>Yeni Oluştur</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soyad" class="control-label"></label>
                <input asp-for="Soyad" class="form-control" />
                <span asp-validation-for="Soyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MusteriId" class="control-label"></label>
                <input asp-for="MusteriId" class="form-control" />
                <span asp-validation-for="MusteriId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KullaniciSifre" class="control-label"></label>
                <input asp-for="KullaniciSifre" class="form-control" />
                <span asp-validation-for="KullaniciSifre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KullaniciKodu" class="control-label"></label>
                <input asp-for="KullaniciKodu" class="form-control" />
                <span asp-validation-for="KullaniciKodu" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="RoleTanim" class="form-label"></label>
                <select asp-for="RoleTanim" asp-items="Html.GetEnumSelectList<RoleTanim>()"></select>
                <span asp-validation-for="RoleTanim" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="OlusturanKullanici" class="control-label"></label>
                <input asp-for="OlusturanKullanici" class="form-control" />
                <span asp-validation-for="OlusturanKullanici" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OlusturanKullaniciId" class="control-label"></label>
                <input asp-for="OlusturanKullaniciId" class="form-control" />
                <span asp-validation-for="OlusturanKullaniciId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuncelleyenKullanici" class="control-label"></label>
                <input asp-for="GuncelleyenKullanici" class="form-control" />
                <span asp-validation-for="GuncelleyenKullanici" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuncelleyenKullaniciId" class="control-label"></label>
                <input asp-for="GuncelleyenKullaniciId" class="form-control" />
                <span asp-validation-for="GuncelleyenKullaniciId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MailBildirim" /> @Html.DisplayNameFor(model => model.MailBildirim)
                </label>
            </div>
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aktif" /> @Html.DisplayNameFor(model => model.Aktif)
                </label>
            </div>
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Silindi" /> @Html.DisplayNameFor(model => model.Silindi)
                </label>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Oluştur" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-warning" asp-action="Index">Listeye Geri Dön</a>
</div>

IsTakip.WebUI/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IsTakip.WebUI</title>
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IsTakip.WebUI.styles.css" asp-append-version="true" />

    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link href="~/metronic/assets/css/style.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/metronic/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap1.css" />
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IsTakip.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Kullanici" asp-action="Index">Kullanıcı</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Depo" asp-action="Index">Depo</a>
                        </li>
                    </ul>
                    @*<div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                        <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked="">
                        <label class="btn btn-outline-primary" for="btnradio1">Radio 1</label>

                        <input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off" checked="">
                        <label class="btn btn-outline-primary" for="btnradio2">Radio 2</label>

                        <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off" checked="">
                        <label class="btn btn-outline-primary" for="btnradio3">Radio 3</label>
                    </div>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IsTakip.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>